//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace desktop1
{
    using System;
    using System.Collections.Generic;
    
    public partial class desktop
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public string Streets { get; set; }
        public string house_number { get; set; }
        public string mobile_number { get; set; }
        public string work_number { get; set; }
        public string home_number { get; set; }
        public string Company { get; set; }
    }
}
