//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace desktop1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class desktopEntities1 : DbContext
    {
        private static desktopEntities1 _context;
        public desktopEntities1()
            : base("name=desktopEntities1")
        {
        }
        public static desktopEntities1 GetContext()
        {
            if (_context == null)
                _context = new desktopEntities1();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abonent_> Abonent_ { get; set; }
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<desktop> desktop { get; set; }
        public virtual DbSet<PhoneNumber> PhoneNumber { get; set; }
        public virtual DbSet<Streets> Streets { get; set; }
    }
}
